import streamlit as st
import pandas as pd
import os

# Set the page configuration
st.set_page_config(page_title="ESLM Insights", page_icon="📊", layout="wide")

# Function to load the data generated by our analysis script
@st.cache_data
def load_data():
    try:
        mttr_by_stage = pd.read_csv("data/processed/mttr_by_stage.csv")
        bottlenecks = pd.read_csv("data/processed/prelive_bottlenecks.csv")
        assets = pd.read_csv("data/processed/cleaned_assets.csv")
        tickets = pd.read_csv("data/processed/cleaned_tickets.csv")
        return mttr_by_stage, bottlenecks, assets, tickets
    except FileNotFoundError:
        st.error("Data files not found. Please run `src/ingestion.py` and `src/analysis.py` first.")
        st.stop()

mttr_by_stage, bottlenecks, assets, tickets = load_data()

# --- HEADER SECTION ---
st.title("📊 Enterprise Service Lifecycle Management (ESLM) Dashboard")
st.markdown("""
*An interactive tool to monitor service reliability, identify friction points, and ensure data quality across the HMRC IT estate.*
""")

st.divider()

# --- KPI METRICS SECTION ---
st.subheader("High-Level Service Health metrics")
col1, col2, col3, col4 = st.columns(4)

total_assets = len(assets)
missing_owners = len(assets[assets['owner_email'] == 'UNASSIGNED_REQUIRES_AUDIT'])
pre_live_avg = mttr_by_stage[mttr_by_stage['stage'] == 'Pre-Live Transition']['avg_resolution_days'].values[0]

with col1:
    st.metric(label="Total Configuration Items (CIs)", value=total_assets)
with col2:
    st.metric(label="Data Quality: Missing Owners", value=missing_owners, delta="- Requires Audit", delta_color="inverse")
with col3:
    st.metric(label="Total Service Tickets", value=len(tickets))
with col4:
    st.metric(label="Avg Pre-Live Transition Time", value=f"{pre_live_avg} Days", delta="Friction Point Detected", delta_color="inverse")

st.divider()

# --- VISUALIZATION SECTION ---
col_left, col_right = st.columns(2)

with col_left:
    st.subheader("1. Mean Time To Resolution (MTTR) by Stage")
    st.markdown("Identifies overarching delays in the service lifecycle.")
    # Streamlit's native bar chart
    st.bar_chart(data=mttr_by_stage.set_index('stage'))

with col_right:
    st.subheader("2. Pre-Live Bottlenecks by CI Type")
    st.markdown("Pinpoints exactly *which* technologies are causing friction during transition.")
    st.bar_chart(data=bottlenecks.set_index('ci_type'))

# --- DATA EXPLORER SECTION ---
st.divider()
st.subheader("🔍 Deep Dive: Unassigned Assets (Data Bedrock Risk)")
st.markdown("To maintain 'Data as a Bedrock', the following assets require immediate ownership assignment:")

unassigned_assets = assets[assets['owner_email'] == 'UNASSIGNED_REQUIRES_AUDIT']
st.dataframe(unassigned_assets, use_container_width=True)